services:
  postgres:
    container_name: jobtrackr-postgres
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: jobtrackr
      POSTGRES_PASSWORD: jobtrackr
      POSTGRES_DB: jobtrackr_db
    volumes:
      - jobtrackr_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  jobtrackr_pg_data:
